
---
apiVersion: v1
kind: Namespace
metadata:
  name: sanjay

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: sanjay
spec:
  containers:
    - name: my-cont1
      image: nginx

